//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_.Net_Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Background> Background { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<FoodStyle> FoodStyle { get; set; }
        public virtual DbSet<Logo> Logo { get; set; }
        public virtual DbSet<Navbar> Navbar { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<OurStrength> OurStrength { get; set; }
        public virtual DbSet<ShopCart> ShopCart { get; set; }
        public virtual DbSet<Social> Social { get; set; }
        public virtual DbSet<Story> Story { get; set; }
        public virtual DbSet<UpcomingEvent> UpcomingEvent { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
